name: Deploy to GitHub Pages

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci
      
    - name: Build website
      run: npx expo export:web
        
    - name: Deploy 🚀
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout -B gh-pages
        mv web-build/* . # Move contents of web-build folder to root
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push -f origin gh-pages
